const Router = require('express')
const router = new Router()
const clientRouter = require('./clientRouter')
const detailRouter = require('./detailRouter')
const employeeRouter = require('./employeeRouter')
const fullservicelistRouter = require('./fullservicelistRouter')
const machineRouter = require('./machineRouter')
const machinetypeRouter = require('./machinetypeRouter')
const manufacturerRouter = require('./manufacturerRouter')
const partnerRouter = require('./partnerRouter')
const positionRouter = require('./positionRouter')
const requestRouter = require('./requestRouter')
const servicelistRouter = require('./servicelistRouter')
const statusRouter = require('./statusRouter')
const workRouter =  require('./workRouter')

router.use('/client', clientRouter)
router.use('/detail', detailRouter)
router.use('/fullservicelist', fullservicelistRouter)
router.use('/employee', employeeRouter)
router.use('/machine', machineRouter)
router.use('/machinetype', machinetypeRouter)
router.use('/manufacturer', manufacturerRouter)
router.use('/partner', partnerRouter)
router.use('/position', positionRouter)
router.use('/request', requestRouter)
router.use('/servicelist', servicelistRouter)
router.use('/status', statusRouter)
router.use('/work', workRouter)

module.exports = router